spring:
  application:
    name: elastic
  jackson:
    serialization:
      INDENT_OUTPUT: true
opensearch:
  host: localhost
  port: 9200
  scheme: http
  username: admin
  password: Random!Password1