server.port=8080

elastic-app.name=elastic

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=testdb

spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=reactive